import React from 'react';

const ToolDesign = () => {
  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-2xl font-bold text-slate-800">AI Generated Design</h2>
        <p className="text-slate-500 text-sm mt-0.5">A beautiful interface crafted entirely by AI tools</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Stats Cards */}
        <div className="card p-6 bg-gradient-to-br from-brand-500 to-brand-700 text-white shadow-lg shadow-brand-500/30">
          <h3 className="text-brand-100 text-sm font-medium">Total Generations</h3>
          <p className="text-4xl font-bold mt-2">12,450</p>
          <div className="mt-4 text-sm bg-white/20 inline-block px-2 py-1 rounded-lg backdrop-blur-sm">
            ↑ 14% this week
          </div>
        </div>
        
        <div className="card p-6 bg-white border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
          <h3 className="text-slate-500 text-sm font-medium">Active Models</h3>
          <p className="text-4xl font-bold text-slate-800 mt-2">4</p>
          <div className="mt-4 flex gap-2">
            <span className="px-2 py-1 bg-green-100 text-green-700 text-xs rounded-md font-medium">YOLOv8</span>
            <span className="px-2 py-1 bg-blue-100 text-blue-700 text-xs rounded-md font-medium">Recommender</span>
          </div>
        </div>

        <div className="card p-6 bg-white border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
          <h3 className="text-slate-500 text-sm font-medium">System Health</h3>
          <p className="text-4xl font-bold text-emerald-600 mt-2">99.9%</p>
          <div className="mt-4 text-sm text-slate-500 flex items-center gap-1">
            <span className="w-2 h-2 rounded-full bg-emerald-500 inline-block"></span>
            All systems operational
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 card p-0 overflow-hidden border border-slate-200 shadow-sm">
          <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
            <h3 className="font-bold text-slate-800">Recent AI Designs</h3>
            <button className="text-sm text-brand-600 font-medium hover:text-brand-700 bg-brand-50 px-3 py-1.5 rounded-lg transition-colors">View All</button>
          </div>
          <div className="p-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="group relative rounded-xl overflow-hidden bg-slate-100 aspect-video border border-slate-200 cursor-pointer">
                <div className="absolute inset-0 bg-gradient-to-t from-slate-900/80 via-slate-900/20 to-transparent opacity-0 group-hover:opacity-100 transition-all duration-300 flex flex-col justify-end p-4 z-10">
                  <span className="text-white font-medium translate-y-2 group-hover:translate-y-0 transition-transform duration-300">Modern Living Room {i}</span>
                  <span className="text-white/70 text-xs mt-1 translate-y-2 group-hover:translate-y-0 transition-transform duration-300 delay-75">Generated by AI</span>
                </div>
                <div className="w-full h-full flex items-center justify-center text-slate-300 group-hover:scale-110 transition-transform duration-500">
                  <span className="text-5xl drop-shadow-sm">🖼️</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="card p-6 border border-slate-200 shadow-sm">
          <h3 className="font-bold text-slate-800 mb-4">Tool Activity</h3>
          <div className="space-y-3">
            {[
              { tool: 'Layout Generator', time: '2 mins ago', status: 'Success' },
              { tool: 'Style Transfer', time: '15 mins ago', status: 'Success' },
              { tool: 'Furniture Matcher', time: '1 hour ago', status: 'Processing' },
              { tool: '3D Renderer', time: '2 hours ago', status: 'Success' },
            ].map((activity, i) => (
              <div key={i} className="flex items-center justify-between p-3 rounded-xl hover:bg-slate-50 border border-transparent hover:border-slate-100 transition-all cursor-pointer">
                <div className="flex items-center gap-3">
                  <div className={`w-2.5 h-2.5 rounded-full shadow-sm ${activity.status === 'Success' ? 'bg-emerald-500 shadow-emerald-500/50' : 'bg-amber-500 shadow-amber-500/50'}`}></div>
                  <div>
                    <p className="text-sm font-medium text-slate-700">{activity.tool}</p>
                    <p className="text-xs text-slate-400">{activity.time}</p>
                  </div>
                </div>
                <span className={`text-xs font-medium px-2.5 py-1 rounded-lg ${
                  activity.status === 'Success' ? 'bg-emerald-50 text-emerald-700 border border-emerald-100' : 'bg-amber-50 text-amber-700 border border-amber-100'
                }`}>
                  {activity.status}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ToolDesign;